FROM python:3.10-slim
WORKDIR /app
COPY requirements-api.txt .
RUN pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install --no-cache-dir --default-timeout=1000 -r requirements-api.txt
COPY . .
# Expose only internally
EXPOSE 8000
CMD ["uvicorn", "security_api:app", "--host", "0.0.0.0", "--port", "8000"]
