services:
  secure-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./ml_models:/app/ml_models
      - ./main.py:/app/main.py
      - ./agent_tools.py:/app/agent_tools.py
      - ./security_api.py:/app/security_api.py
    environment:
      - NVIDIA_API_KEY=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
      - SUPABASE_URL=https://rtjskltssmpymtxeelua.supabase.co
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0anNrbHRzc21weW10eGVlbHVhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDM3MDg4NSwiZXhwIjoyMDg5OTQ2ODg1fQ.rerqqOuw8zMok3j6blQyA1Ag_QyaZCD6Ji8H6X6R9OM
      - JWT_SECRET_KEY=8cf2c4e4e429acffb069eaecf45f69321c7c608c73fd17ef55eecbd84f25115e
      - INTERNAL_API_KEY=OLEA_INTERNAL_GATEWAY_KEY_2026

  frontend-agent:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8502:8501"
    volumes:
      - ./app.py:/app/app.py
      - ./auth_ui.py:/app/auth_ui.py
    environment:
      - API_URL=http://secure-api:8000/api/secure_claim
      - NVIDIA_API_KEY=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
      - SUPABASE_URL=https://rtjskltssmpymtxeelua.supabase.co
      - SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0anNrbHRzc21weW10eGVlbHVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNzA4ODUsImV4cCI6MjA4OTk0Njg4NX0.lyyIFU5vaFqt8rKdEBeXKJzxUZB2kYvjxKgUCJeKKO4
      - SUPABASE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0anNrbHRzc21weW10eGVlbHVhIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3NDM3MDg4NSwiZXhwIjoyMDg5OTQ2ODg1fQ.rerqqOuw8zMok3j6blQyA1Ag_QyaZCD6Ji8H6X6R9OM
      - INTERNAL_API_KEY=OLEA_INTERNAL_GATEWAY_KEY_2026
    depends_on:
      - secure-api
